-- Supabase Auth + profiles + follows schema
-- Run in Supabase SQL editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  avatar_url text,
  favorite_team_id bigint references public.teams(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null check (target_type in ('team', 'player')),
  target_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, target_type, target_id)
);

create index if not exists follows_user_idx on public.follows(user_id);
create index if not exists follows_target_idx on public.follows(target_type, target_id);

create table if not exists public.news_likes (
  id bigint generated by default as identity primary key,
  news_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (news_id, user_id)
);

create table if not exists public.news_comments (
  id bigint generated by default as identity primary key,
  news_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  comment_text text not null check (char_length(comment_text) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists news_likes_news_idx on public.news_likes(news_id);
create index if not exists news_comments_news_idx on public.news_comments(news_id);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.follows enable row level security;
alter table public.news_likes enable row level security;
alter table public.news_comments enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'profiles_select_own'
  ) then
    create policy profiles_select_own on public.profiles for select using (auth.uid() = id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'profiles_insert_own'
  ) then
    create policy profiles_insert_own on public.profiles for insert with check (auth.uid() = id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'profiles_update_own'
  ) then
    create policy profiles_update_own on public.profiles for update using (auth.uid() = id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'follows' and policyname = 'follows_manage_own'
  ) then
    create policy follows_manage_own on public.follows for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'news_likes' and policyname = 'news_likes_read_all'
  ) then
    create policy news_likes_read_all on public.news_likes for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'news_likes' and policyname = 'news_likes_manage_own'
  ) then
    create policy news_likes_manage_own on public.news_likes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'news_comments' and policyname = 'news_comments_read_all'
  ) then
    create policy news_comments_read_all on public.news_comments for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'news_comments' and policyname = 'news_comments_insert_own'
  ) then
    create policy news_comments_insert_own on public.news_comments for insert with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'news_comments' and policyname = 'news_comments_update_own'
  ) then
    create policy news_comments_update_own on public.news_comments for update using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'news_comments' and policyname = 'news_comments_delete_own'
  ) then
    create policy news_comments_delete_own on public.news_comments for delete using (auth.uid() = user_id);
  end if;
end $$;
